// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hoblzquflimxfluishcf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhvYmx6cXVmbGlteGZsdWlzaGNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3ODczODAsImV4cCI6MjA3MTM2MzM4MH0.nTvcROgZrY3RoHzqr07vP6cBaAB0JgItBcm6WO8pE20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});